// 博客文章数据（硬编码示例，后续可接入 MDX）

export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  date: string; // ISO 日期字符串
  author: string;
  tags: string[];
  content: string[]; // 文章段落（按顺序渲染）
};

export const posts: Post[] = [
  {
    slug: "getting-started-with-json",
    title: "Getting Started with JSON: A Beginner's Guide",
    excerpt:
      "Learn what JSON is, why it powers the modern web, and how to read and write it correctly.",
    date: "2026-01-12",
    author: "ToolHub Team",
    tags: ["JSON", "Beginner", "Web"],
    content: [
      "JSON, short for JavaScript Object Notation, is a lightweight format for storing and transporting data. It has become the de-facto standard for exchanging data between a server and a web application, and almost every modern API speaks JSON.",
      "At its core, JSON is built on two structures: a collection of name/value pairs (objects) and an ordered list of values (arrays). This simplicity is exactly why it is so popular. A JSON object is written inside curly braces, with keys as strings and values that can be strings, numbers, booleans, arrays, objects, or null.",
      "One of the most common mistakes beginners make is leaving trailing commas or using single quotes. JSON is strict: keys and string values must be wrapped in double quotes, and no trailing comma is allowed after the last item. These small rules are why a JSON formatter or validator is one of the first tools developers reach for.",
      "When you are working with JSON in code, you typically parse it into an object with JSON.parse() and turn an object back into a string with JSON.stringify(). If the input is invalid, JSON.parse() throws an error, which is why validating your JSON before using it in production is a good habit.",
      "Once you understand the basics, JSON opens the door to working with almost any API on the internet. Try pasting a real API response into a JSON formatter to see its structure clearly, and you will quickly feel at home reading nested data.",
    ],
  },
  {
    slug: "understanding-web-performance",
    title: "Understanding Web Performance and Core Web Vitals",
    excerpt:
      "A practical overview of the metrics that matter for fast, user-friendly websites.",
    date: "2026-02-03",
    author: "ToolHub Team",
    tags: ["Performance", "SEO", "Web"],
    content: [
      "Web performance is no longer a nice-to-have. It directly affects user experience, search rankings, and even revenue. Google measures real-world performance through a set of metrics called Core Web Vitals, and understanding them helps you build sites that feel fast.",
      "The three Core Web Vitals are Largest Contentful Paint (LCP), which measures loading performance and should happen within 2.5 seconds; Interaction to Next Paint (INP), which measures responsiveness and should be under 200 milliseconds; and Cumulative Layout Shift (CLS), which measures visual stability and should stay below 0.1.",
      "Improving LCP usually means serving your largest visible element faster. That involves optimizing images, reducing server response time, and removing render-blocking resources. A fast, well-cached server and properly sized images go a long way.",
      "INP replaced First Input Delay as the responsiveness metric. To keep it low, avoid long tasks on the main thread, break up heavy JavaScript, and defer non-critical work. The goal is for the page to respond to user input almost instantly.",
      "CLS is all about visual stability. Always include width and height attributes on images and videos, reserve space for ads, and avoid inserting content above existing content. Small layout shifts accumulate and frustrate users.",
      "Measuring is the first step. Use tools like Lighthouse, PageSpeed Insights, and the Chrome User Experience Report to get real data. Optimize iteratively, measure again, and keep your site fast for every visitor.",
    ],
  },
  {
    slug: "choosing-the-right-online-tool",
    title: "How to Choose the Right Online Tool for Your Workflow",
    excerpt:
      "Not all online tools are equal. Here is how to pick ones that are safe, fast, and private.",
    date: "2026-03-08",
    author: "ToolHub Team",
    tags: ["Productivity", "Tools", "Workflow"],
    content: [
      "Online tools can save hours of repetitive work, but choosing the wrong one can cost you in hidden ways. The best tools are fast, focused, and respectful of your data. Here are a few principles to keep in mind.",
      "First, prefer tools that run entirely in your browser. When a tool processes your input locally with JavaScript, your data never leaves your device. This is especially important for sensitive content like configuration files or credentials.",
      "Second, look for tools that are simple and do one thing well. A focused tool has a shorter learning curve, fewer bugs, and is easier to trust. Feature creep often leads to confusing interfaces and slower performance.",
      "Third, consider performance and reliability. A tool that loads instantly and works offline-friendly is a tool you will actually use every day. Heavy, ad-bloated pages get in the way of getting work done.",
      "Finally, check whether the tool is maintained and whether it documents how your data is handled. A clear privacy policy is a good sign that the creators take your trust seriously.",
      "At ToolHub, every tool runs in your browser, keeps your data private, and is built to be fast. Bookmark the ones you use often, and your daily workflow will thank you.",
    ],
  },
  // 追加的 5 篇原创技术博客
  {
    slug: "base64-encoding-explained",
    title: "Base64 Encoding Explained: When and Why to Use It",
    excerpt:
      "A practical guide to what Base64 is, where it shines, and the cases where you should avoid it.",
    date: "2026-03-20",
    author: "ToolHub Team",
    tags: ["Base64", "Web", "Encoding"],
    content: [
      "Base64 is an encoding scheme that converts binary data into a sequence of printable ASCII characters. It works by treating every three bytes of input as four 6-bit groups, then mapping each group to one of 64 characters drawn from the alphabet A-Z, a-z, 0-9, plus the symbols + and /. The reason this matters is that many older transport layers and text-based protocols were designed around ASCII and choke on raw bytes that look like control characters or null terminators. By packing binary data into a safe subset of ASCII, Base64 lets you push images, certificates, or serialized objects through channels that were never designed for binary. The trade-off is simple but important: every three bytes of source data become four bytes of Base64, so the output is roughly 33 percent larger than the input.",
      "The most common place you will meet Base64 in the wild is the data URI scheme, where small assets like icons or placeholder images get embedded directly into CSS or HTML to avoid an extra HTTP request. Email attachments use it through MIME, because SMTP was originally designed to carry only ASCII text and would corrupt raw binary. JSON Web Tokens encode their header and payload as Base64URL, a variant that swaps + and / for - and _ so the result is URL-safe. HTTP Basic Authentication also uses it to transmit credentials in the Authorization header, which is a useful reminder that Base64 is transport encoding and not a security boundary, since anyone who captures the header on the wire can reverse it in seconds.",
      "Despite its popularity, Base64 is frequently misused. The most common mistake is treating it as encryption, which it absolutely is not. The algorithm is well documented, deterministic, and reversible by anyone with a terminal. The second mistake is using it for large files. A 10 MB image becomes roughly 13.3 MB of Base64, and you lose the ability to stream it or serve it through a CDN efficiently. Browsers also cannot cache individual Base64 assets the way they cache separate files, so embedding everything as data URIs can actually slow down repeated visits. If you find yourself Base64-encoding megabytes of data, you are usually better off serving the file through a proper endpoint and letting a CDN handle the caching.",
      "In the browser, the built-in btoa and atob functions are the standard way to encode and decode Base64. They are fast and synchronous, but they only accept strings whose characters fall in the Latin1 range. The moment you try to encode a string containing emoji, CJK characters, or anything outside that range, btoa throws a DOMException. The classic workaround is the escape and unescape trick: btoa(unescape(encodeURIComponent(str))) on encode and decodeURIComponent(escape(atob(b64))) on decode. It works everywhere but relies on deprecated functions. A cleaner, modern approach is to use TextEncoder to get a UTF-8 byte array, then convert those bytes to Base64 with a small helper or the FileReader API. The browser does not yet expose a native Base64 stream codec, but the newer Buffer and WebCodecs APIs are slowly closing that gap.",
      "Online Base64 tools come in handy when you need to encode or decode a small payload quickly without writing code. Typical scenarios include debugging a JWT in the browser, inspecting an inline data URI, or verifying that a Base64 value matches a known source. For anything sensitive, the tool should run entirely client-side so the data never touches a server. This is especially important for credentials, API tokens, or certificate fragments that might be embedded in a Base64 string. A good client-side tool will also handle UTF-8 correctly, detect padding errors, and offer a URL-safe variant toggle. For batch work or anything beyond a few kilobytes, a local script with Node's Buffer or Python's base64 module is usually the better fit, because you get full control over encoding and can integrate it into a pipeline.",
    ],
  },
  {
    slug: "password-security-best-practices",
    title: "Password Security: Best Practices for 2026 and Beyond",
    excerpt:
      "Length over complexity, password managers, and why your old password rules are probably wrong.",
    date: "2026-04-05",
    author: "ToolHub Team",
    tags: ["Security", "Passwords", "Privacy"],
    content: [
      "The 2024 update to NIST Special Publication 800-63B quietly retired most of the password advice you grew up with. The new guidance says you should stop forcing users to include special characters, stop requiring periodic password resets, and start screening new passwords against known compromised lists. The reason is empirical: when users are forced to add an exclamation mark or replace letters with numbers, they produce predictable patterns like Password1! that fall to dictionary attacks just as fast as simpler passwords. What actually matters is length. A 16-character passphrase made of unrelated words has more entropy than an 8-character string with every complexity rule applied. Modern guidance also encourages password managers as part of the solution rather than fighting against them. The bottom line is to drop the composition rules, raise the minimum length to at least 12 characters, and focus on what attackers actually do rather than what makes passwords look secure.",
      "Passphrases are the simplest way to combine strength and memorability. A phrase like \"river-mango-tractor-window\" has around 60 bits of entropy yet is straightforward for a human to remember and type. Compare that with \"Tr0ub4dor&3\", which is famously hard to remember, easy to mistype, and offers less actual entropy than the passphrase. The math favors longer passphrases because each additional word multiplies the search space by the size of the dictionary, while short passwords only multiply by a much smaller set of characters. For accounts that you log into by typing, especially on mobile keyboards, passphrases win on every axis: stronger, easier to remember, and less frustrating. The trick is choosing words that are unrelated to each other and to your personal life, so an attacker who knows your hobby cannot guess them through context.",
      "A password manager is no longer optional for anyone with more than a handful of accounts. Tools like Bitwarden and 1Password generate a unique, long, random password for every site, store them in an encrypted vault, and fill them in automatically. The only password you need to remember is the master password, which should itself be a strong passphrase. The major objection, the worry about \"what if the manager gets hacked?\", is real but overstated. Reputable managers encrypt the vault on your device before it ever syncs, so a breach of the server exposes only encrypted blobs. The alternative, reusing a few memorable passwords, is far more dangerous because one site breach puts every other account at risk. If you have not used a manager before, start with a free tier, import your existing logins, and gradually replace reused passwords as you encounter them.",
      "Credential stuffing is the attack that turns one breach into many. Attackers take leaked username and password pairs from one compromised site and try them on hundreds of others. Because reuse is so common, the success rate is shockingly high. Even a strong password, if reused, becomes weak the moment any service you used it on gets breached and the hash is cracked. The defense is mechanical: never reuse passwords across accounts, especially not for email, banking, or your password manager. Two-factor authentication helps a great deal by blocking the attack even when the password matches, but it is not a substitute for unique credentials. If you have reused passwords in the past, prioritize the high-value accounts first, then work through the rest. Most password managers can flag duplicates for you.",
      "Two-factor authentication adds a second proof of identity beyond your password, and it blocks the vast majority of automated account takeover attempts. Not all second factors are equal, however. SMS-based codes are the weakest option because they are vulnerable to SIM swapping, interception, and SS7 attacks. Time-based one-time passwords, generated by apps like Authy, 1Password, or Aegis, are stronger because they live on your device and never travel over the network. Hardware security keys like YubiKey are stronger still, as they resist phishing by verifying the domain you are logging into. Wherever a service supports it, prefer TOTP or hardware keys over SMS. The small inconvenience of typing a six-digit code is well worth blocking the kind of automated attacks that compromise millions of accounts every year.",
      "The simplest way to know whether a password has already been exposed is to check it against the Have I Been Pwned database. The service offers a k-anonymity API: you send only the first five characters of the password's SHA-1 hash, and HIBP replies with a list of matching hash suffixes along with how many times each has appeared in a known breach. Because you only ever send a partial hash, the server never learns your actual password. Most password managers can perform this check automatically and warn you when a stored password appears in a breach. The same database powers breach alerts built into Chrome, Firefox, and Safari. If you find one of your current passwords in the list, change it everywhere you have used it, and do not reuse the new one anywhere else.",
      "When you use an online password generator, the most important property is that the random bytes are produced on your device and never sent over the network. A surprising number of free generators run on the server and could log every password they create. Before using one, check the page source or the privacy policy to confirm it is client-side only. Other useful properties include adjustable length, the ability to exclude ambiguous characters like l and 1 or O and 0, and support for different character sets such as alphanumeric, diceware, or hex. If you are generating a password that you will store in a manager anyway, aim for at least 16 random characters. For passphrases, four or five unrelated words from a large wordlist strike a good balance between strength and usability.",
    ],
  },
  {
    slug: "markdown-cheatsheet-guide",
    title: "The Markdown Cheatsheet Every Developer Should Bookmark",
    excerpt:
      "All the Markdown syntax you actually use, with examples and common pitfalls.",
    date: "2026-04-18",
    author: "ToolHub Team",
    tags: ["Markdown", "Documentation", "Web"],
    content: [
      "Markdown represents headings with one to six hash symbols followed by a space. A single hash is an H1, two is an H2, and so on through six. Always leave a space after the hashes, because ##Heading will not render as a heading in most parsers while ## Heading will. Most codebases use only one H1 per document for SEO and accessibility reasons, and reserve H2 through H4 for sections and subsections. Some flavors also support an alternative syntax where you underline the heading with equals signs for H1 or dashes for H2, but this is rarely used in modern documentation. When you are writing for a static site generator, the heading level often feeds into the table of contents, so keep the hierarchy consistent. Skipping from H2 to H4 may render fine but will confuse screen readers and TOC generators.",
      "For inline emphasis, Markdown gives you several overlapping options. Wrapping text in single asterisks or single underscores produces italic text, while double asterisks or double underscores produce bold. The strikethrough extension, which uses double tildes, is widely supported after being popularized by GitHub Flavored Markdown. Inline code is wrapped in single backticks, and if you need a backtick inside the code, you can use double or triple backticks as the delimiter. The choice between asterisks and underscores is mostly stylistic, but asterisks are safer when you are dealing with text that contains underscores, like variable names or URLs. Be careful with word-internal underscores: most parsers treat them as literal characters inside a word, which is why snake_case identifiers render correctly.",
      "Lists are the most error-prone part of Markdown. Unordered lists start with a dash, asterisk, or plus followed by a space. Ordered lists start with a number followed by a period. The number you write does not actually determine the output number in strict Markdown, since the first item becomes 1, the second becomes 2, and so on, but most renderers now respect the actual numbers you type. Nested lists require a consistent indentation level, usually two or four spaces depending on the parser. The single most common bug is forgetting to leave a blank line between a paragraph and the list that follows it. Without that blank line, many parsers treat the list items as part of the paragraph and refuse to render the bullets at all.",
      "Links come in two flavors: inline and reference. An inline link uses the pattern [text](url), with the URL optionally followed by a title in quotes. A reference link splits the link into two parts: [text][id] where you write the text, and elsewhere in the document [id]: url followed by an optional title. Reference links are useful when you have a long URL that would break the flow of a paragraph, or when you reuse the same link many times. Images follow the same syntax but with a leading exclamation mark: ![alt text](image-url). For complex documents, reference-style images keep the source readable. One pitfall worth knowing: the alt text is required for accessibility, and it should describe the image rather than just repeat the surrounding paragraph.",
      "Code in Markdown is either inline or fenced. Inline code, as mentioned earlier, is wrapped in single backticks. Fenced code blocks use three backticks at the start and end, and you can specify a language after the opening fence to enable syntax highlighting. The language hint is optional, but omitting it means the renderer will fall back to plain text and you lose color coding. Common values include js, ts, python, bash, json, and yaml, though many renderers also accept longer aliases like javascript. For code that itself contains backticks, you can use four or more backticks as the fence so the inner content is treated literally. Avoid indenting code with four spaces unless you are targeting a parser that only supports the original Markdown syntax, because the fenced form is more readable and easier to copy.",
      "Blockquotes start with a greater-than sign followed by a space. They can be nested with additional levels of the marker, and they can contain other Markdown elements like lists or code blocks. Horizontal rules are produced by three or more hyphens, asterisks, or underscores on a line by themselves. Tables, originally a GitHub extension, are now widely supported. They use pipes to separate columns and a row of dashes to separate the header from the body. Alignment can be set by placing colons in the dash row: a colon on the left for left-aligned, on the right for right-aligned, and on both sides for centered. Tables are handy for small reference data but become unwieldy for anything with many columns or long cell content. For complex layouts, fall back to HTML.",
      "The most common Markdown pitfalls are syntactic. Forgetting a blank line before a list will collapse the list into the preceding paragraph. Mixing tabs and spaces for indentation will break nested lists in unpredictable ways. Putting a pipe character inside a table cell requires escaping with a backslash. HTML and Markdown can be mixed, but the parser stops processing Markdown inside a block-level HTML element, so anything you write between a div opening and closing tag is treated as literal HTML. The safest approach is to use HTML only for things Markdown cannot express, like a details disclosure widget, and stick to Markdown for everything else. When in doubt, preview your Markdown before publishing, because the rendering differences between CommonMark, GitHub Flavored Markdown, and various static site generators are real.",
      "GitHub Flavored Markdown adds several extensions that have become near-universal. Task lists are created by writing - [ ] or - [x] inside a list item, and they render as clickable checkboxes on GitHub. Strikethrough with double tildes is part of GFM and is supported by most modern renderers. Autolink turns bare URLs into clickable links without requiring the angle-bracket syntax. Tables, as mentioned, were popularized by GFM. There are also extensions that are less universal: footnotes, definition lists, and math notation through LaTeX. If you are writing for a specific platform, check which extensions it supports before relying on them. For portable documentation, stick to the CommonMark core plus the most established GFM extensions, and your Markdown will render correctly almost everywhere.",
    ],
  },
  {
    slug: "understanding-http-status-codes",
    title: "HTTP Status Codes: A Field Guide for Developers",
    excerpt:
      "From 200 to 451, the status codes you meet every day and what they really mean.",
    date: "2026-05-02",
    author: "ToolHub Team",
    tags: ["HTTP", "Web", "API"],
    content: [
      "HTTP status codes are grouped into five classes, identified by the first digit of the three-digit code. Codes in the 1xx range are informational and tell the client to keep waiting for a final response. The 2xx range marks successful requests. The 3xx range is for redirection, telling the client the resource is somewhere else. The 4xx range indicates client errors, meaning the request as sent cannot be fulfilled. The 5xx range indicates server errors, meaning the server failed to handle an otherwise valid request. This grouping is more than a convention, since many HTTP libraries and proxies branch on the first digit, and tools like curl treat 4xx and 5xx differently from 2xx. When you are designing an API or debugging a failing request, the class alone tells you where to look: 4xx means the client did something wrong, 5xx means the server did.",
      "The 200 OK response is the default success code, and it means the server is returning the requested representation in the body. 201 Created is more specific: it should be used when a POST request has successfully created a new resource, and the response should include a Location header pointing to the new resource's URL. 204 No Content means the request succeeded but there is no body to return, which is the right choice for a successful DELETE or a PUT that updates a resource without returning it. The distinction matters for clients that react to the status code rather than parsing the body. Returning 200 with an empty body for a delete operation technically works but loses information for client libraries that use the status code to decide whether to refresh a list. Pick the code that says exactly what happened.",
      "Redirects are subtle, and the difference between them comes down to whether the HTTP method is preserved. 301 Moved Permanently tells the client that the resource has moved and that future requests should use the new URL. Historically, some clients changed POST to GET on a 301, which led to confusion. 302 Found is the temporary equivalent, but it has the same method-changing behavior. To fix this, HTTP/1.1 introduced 307 Temporary Redirect and 308 Permanent Redirect, both of which preserve the original HTTP method. In practice, 308 should replace 301 for permanent moves where you want POST to stay POST, and 307 should replace 302 for temporary moves. Search engines treat 301 and 308 similarly for SEO purposes, but the method-preservation difference matters when you are redirecting form submissions or API calls.",
      "The 4xx range covers errors caused by the client. 400 Bad Request is the catch-all for malformed input, such as invalid JSON or missing required fields. 401 Unauthorized actually means unauthenticated, since the request lacks valid authentication credentials, and the response should include a WWW-Authenticate header. 403 Forbidden means the server understood the request and authenticated the user, but refuses to authorize the action. The difference between 401 and 403 trips up many API designers: 401 asks \"who are you?\", while 403 says \"I know who you are, and you cannot do this.\" 404 Not Found is the most familiar, returned when the resource does not exist or the server does not want to confirm its existence to an unauthorized user. 429 Too Many Requests is the rate-limiting code, and it should include a Retry-After header telling the client when to try again.",
      "The 5xx range indicates the server failed to handle a valid request. 500 Internal Server Error is the generic catch-all for unhandled exceptions, and it usually means a bug in the application code. 502 Bad Gateway means a proxy or gateway received an invalid response from an upstream server, which often points to a crash or timeout in a backend service. 503 Service Unavailable means the server is temporarily unable to handle the request, usually due to maintenance or overload, and should include a Retry-After header. 504 Gateway Timeout means a proxy did not receive a response from the upstream server in time. When you are debugging, the specific 5xx code tells you where to look: 500 is your application, 502 and 504 are usually infrastructure or a backend you depend on, and 503 is often intentional.",
      "A few less-common status codes are worth knowing. 422 Unprocessable Entity comes from WebDAV but is widely used in APIs to indicate that the request was well-formed syntactically but semantically invalid, for example trying to create an account with an email that is already taken. It is more precise than 400 for validation errors. 418 I'm a Teapot is an April Fools' joke from RFC 2324 that some servers return as an Easter egg; never use it in a real API. 451 Unavailable For Legal Reasons indicates the resource is unavailable due to legal demand, such as government censorship; it is used by sites like GitHub to signal takedowns. 409 Conflict is useful when a request conflicts with the current state of the resource, like trying to create a duplicate. Knowing these codes lets you build APIs that communicate errors precisely rather than overloading 400 and 500 for everything.",
      "When designing an API, the goal is to return a status code that lets the client react correctly without parsing the body. Use 2xx codes that match the action: 201 for creation, 204 for deletion, 200 for general retrieval and updates. Use 4xx codes that describe the client's mistake: 400 for malformed input, 401 for missing auth, 403 for insufficient permissions, 404 for missing resources, 409 for conflicts, 422 for semantic validation errors, 429 for rate limits. Reserve 5xx for genuine server failures, and never use 500 as a default error handler for things like validation errors, because that prevents clients from distinguishing their mistakes from your outages. Include a consistent error body with a machine-readable code and a human-readable message. Document the codes you use, and resist the temptation to invent custom ones unless you also control the client that consumes them.",
      "When something goes wrong with a web request, the browser's DevTools Network panel is your first stop. Open it, reproduce the request, and look at the Status column. A 4xx tells you the request was wrong, so inspect the request headers and body to see what the client actually sent. A 5xx tells you the server failed, so check the server logs if you can and look at the response body for an error message. For APIs, the response body usually contains a structured error that points to the specific field or rule that failed. The Network panel also shows the timing breakdown, which helps distinguish a slow server from a slow network. Use the \"Copy as cURL\" option to reproduce the exact request in a terminal, and use the \"Replay\" feature in some browsers to retry without navigating. Reading status codes carefully turns a vague \"it doesn't work\" into a precise, fixable problem.",
    ],
  },
  {
    slug: "color-formats-hex-rgb-hsl",
    title: "HEX, RGB, and HSL: Choosing the Right Color Format",
    excerpt:
      "Three ways to describe color in CSS, and the situations where each one wins.",
    date: "2026-05-15",
    author: "ToolHub Team",
    tags: ["CSS", "Design", "Color"],
    content: [
      "CSS gives you three main ways to describe a color: hex, RGB, and HSL. A hex color is a hash followed by six hexadecimal digits, where the first two represent red, the next two green, and the last two blue, like #ff6600. A three-digit shorthand expands each digit, so #f60 is equivalent to #ff6600. RGB functions take three numbers from 0 to 255, as in rgb(255, 102, 0), and an optional alpha channel as a fourth value between 0 and 1, as in rgba(255, 102, 0, 0.5). HSL takes three values too, but they describe hue as an angle from 0 to 360, saturation as a percentage, and lightness as a percentage, as in hsl(20, 100%, 50%). All three formats describe the same sRGB color space, so any color you can write in one you can convert to the others without loss. The choice is mostly about readability and what you need to do with the value.",
      "Hex is the workhorse of web color. It is compact, unambiguous, and supported everywhere, including places that historically did not accept CSS functions, like the color attribute in SVG or older attributes on form elements. The six-digit form is the most common, and the three-digit shorthand is convenient for colors where each channel's two digits are the same. Hex is also the format that survives best in configuration files, build scripts, and JSON, because it is a single string with no spaces or commas to escape. When you are working with CSS custom properties, hex is the easiest value to swap out at runtime. The main drawback is that hex does not natively express alpha, so you have to use the eight-digit form like #ff660080, which is less widely understood, or fall back to rgba. Hex is also harder to read when you want to make small perceptual adjustments, since the relationship between the digits and the perceived color is not intuitive.",
      "RGB and RGBA describe colors by their red, green, and blue components, which mirrors how displays emit light. The format is verbose compared to hex, but it has one major advantage: native support for an alpha channel. RGBA takes a fourth value between 0 and 1, or a percentage, that controls opacity, which is exactly what you need for translucent overlays, hover states, and layered backgrounds. RGB and hex are functionally equivalent for opaque colors, since rgb(255, 102, 0) and #ff6600 describe the same color, so the choice between them is often a matter of team convention. RGBA's real value shows up in design systems where you need to tint a brand color at several opacities; expressing it as rgba(var(--brand), 0.2) is clearer than the eight-digit hex equivalent. The modern syntax also allows space-separated values like rgb(255 102 0 / 50%), which is more readable and aligns with the new color functions.",
      "HSL is where color becomes intuitive. Hue is an angle on the color wheel, saturation is how vivid the color is, and lightness is how bright it is. Want a darker version of a brand color? Drop the lightness by 10 percent. Want a softer version? Lower the saturation. Want a complementary color? Add 180 to the hue. These are operations you can do in your head, which is impossible with hex or RGB. HSL really shines when generating color palettes: a monochromatic palette is just the same hue at different lightness levels, an analogous palette is hues within 30 degrees of each other, and a triadic palette is hues 120 degrees apart. Most design systems that expose theming to users do so through HSL or HSL-derived tokens, because designers think in hue and saturation, not in hex codes. The one thing to watch is that HSL lightness is not perceptually uniform, so a 50 percent lightness yellow looks very different from a 50 percent lightness blue.",
      "Modern CSS introduces the color() function, which lets you specify colors in any supported color space using a consistent syntax. You can write color(display-p3 1 0.4 0) to target the Display-P3 wide-gamut space used by modern Apple displays, or color(rec2020 ...) for an even wider space. This matters because sRGB, the space that hex and HSL describe, cannot represent the most saturated reds, greens, and cyans that current hardware can display. If you are building for HDR-capable screens or working with photography, the wider gamut lets you use colors that simply did not exist on the web before. For most projects, sticking with sRGB is still the safe default, because every display supports it and the colors will look consistent. When you do want to opt in, use color() with a fallback for browsers that do not support it yet, and test on actual hardware, since the difference between P3 and sRGB is most visible on saturated colors and is easy to overestimate on a non-P3 monitor.",
      "The format you pick should match the job. For a simple static website with a fixed palette, hex is the right choice: it is short, universal, and easy to copy from a design file. For semi-transparent overlays, hover states, or anywhere you need to control opacity inline, RGBA is clearer than the eight-digit hex form. For design systems, especially those that expose theming or generate palettes programmatically, HSL is the best fit because the values map to how designers think. Many component libraries use CSS custom properties in HSL, like hsl(var(--brand-h) var(--brand-s) var(--brand-l)), so they can be overridden per theme without rewriting every rule. If you are working with wide-gamut content, color() with a P3 space is appropriate, but make sure you provide an sRGB fallback. There is no single best format; the right choice depends on whether you are hand-writing a value, generating it, or overriding it at runtime.",
      "Color contrast is an accessibility requirement, not a design preference. The Web Content Accessibility Guidelines specify a minimum contrast ratio of 4.5:1 for normal text and 3:1 for large text, with stricter 7:1 and 4.5:1 ratios for AAA conformance. Failing contrast is one of the most common accessibility issues on the web, and it is usually a matter of choosing a slightly darker shade or a different background. The format you write the color in does not affect the ratio, but HSL makes it easy to nudge lightness in 5 percent steps until you meet the threshold. When you are designing a system, define your palette in HSL and test every text-on-background combination with a contrast checker. Keep in mind that contrast is measured against the perceived luminance, so two colors that look very different can still fail the ratio. Automated tools like Lighthouse and axe will flag failures, but designing for contrast from the start is faster than fixing it later.",
      "A good color workflow combines a few tools. A picker like the one built into your browser's DevTools lets you sample colors from anywhere on the page and copy them in any format. A contrast checker, whether built into DevTools or as a separate site, tells you instantly whether a pair meets WCAG. A palette generator like Coolors or the HSL-based tools in Figma helps you build a coherent set of colors with consistent hue and saturation. A converter is useful when a design file gives you hex but your system expects HSL, or vice versa; most modern tools handle this conversion automatically, but a standalone converter is handy for quick checks. For wide-gamut work, a tool that shows you the P3 versus sRGB difference side by side helps you decide whether the wider gamut is worth the added complexity. The goal is to pick tools that get out of your way and let you focus on the design decisions.",
    ],
  },
];

export function getPostBySlug(slug: string): Post | undefined {
  return posts.find((post) => post.slug === slug);
}
